### DISCUSSION TITLE
Must PH18-3024 Plus

### DISCUSSION THREAD

**Discussion by alexsobolev1076** [vladyspavlov/esphome-must-inverter#1] [General]
There is a fully work and stable conifig for Inverter Must PH18-3024 Plus - Home Assistant communication.

Hardware setup: 
- WeMos D1 mini PRO 4M (ESP8266 USB)
- UART TTL to RS485 Two-way Converter Module 
- Pigtail IPX1 (U.FL) - RP-SMA (needs to resolder R0 jumper resistor on Esp board) *
- Antenna 2.4GHz 5dBi RP-SMA*
* - optionally, if signal is weak and unstable

Wiring (Thanks to @taHC81)
![MUST-RS485-WemosD1mini](https://github.com/user-attachments/assets/ad1ef2dc-be87-4d9d-a627-5b3eaf4c234b)

![photo_2024-10-20_21-11-31](https://github.com/user-attachments/assets/1da7107e-48ec-429b-a463-a268c0f23290)
![photo_2024-10-20_21-11-31 (2)](https://github.com/user-attachments/assets/0a9dce69-73ae-4b78-a389-9c14fbfa9fbb)
![photo_2024-10-20_21-25-12](https://github.com/user-attachments/assets/4f041ffc-9c7b-4a2a-a008-ce19344dd3dc)

I will highly recommend to mount Esp board as far as possible from inverter because of its significant interference that affects to Wifi radio module. You can also use external 5v power supply for WeMos D1 powering (not from Inverter USB port only).

Working software part:
[Must PH18.zip](https://github.com/user-attachments/files/18021836/Must.PH18.zip)

**Comment by alexsobolev1076** [comment]
There are some custom sensors tempates you might need to paste into your configuration yaml file (for Sunsynk Power Flow lovelace card and Energy Dashboard)

 Approx. Battery SOC (AGM, Flooded, Gel,  Lead):
```yaml
compensation:
  battery_soc_from_voltage:
    unique_id: battery_soc
    source: sensor.must_battery_voltage
    degree: 5
    unit_of_measurement: '%'
    upper_limit: true
    data_points:
      - [27.2, 100]
      - [26.2, 90]
      - [25.9, 80]
      - [24.7, 70]
      - [24.4, 50]
      - [24.2, 40]
      - [24, 30]
      - [23.9, 20]
      - [23, 10]
      - [22, 0]
    
#inverted values
template:
  - sensor:
      - name: Battery SOC inv
        unit_of_measurement: "%"
        state: "{{ states('sensor.compensation_sensor_must_battery_voltage') | float(2) | abs }}"
```
Positive and negative only values from Battery charge power sensor (and other combined values sensors with pos and negatives output values):
```yaml
template:
  - sensor:
      - name: Battery charge power positive only
        state_class: measurement 
        device_class: power
        unit_of_measurement: W
        state: "{{ 0 if states('sensor.must_battery_charge_power')|float(0) < 0 else states('sensor.must_battery_charge_power') }}"
        availability: "{{ has_value('sensor.must_battery_charge_power') }}"

      - name: Battery charge power negative only
        state_class: measurement 
        device_class: power
        unit_of_measurement: W
        state: "{{ 0 if states('sensor.must_battery_charge_power')|float(0) > 0 else states('sensor.must_battery_charge_power') }}"
        availability: "{{ has_value('sensor.must_battery_charge_power') }}"
```
Code examples how to invert values (negative to positive and vice versa):
```yaml
template:
  - sensor:
      - name: Actual Batt voltage inv
        unit_of_measurement: "V"
        state: "{{ states('sensor.must_battery_voltage') | float(1) | abs }}"

      - name: Battery charging power Actual
        unit_of_measurement: "W"
        state: "{{ -1 * states('sensor.battery_charge_power_negative') | float(1) }}"
```

You can create custom daily energy consumption sensors for Energy Dashboard by using Helpers - create "Riemann sum integral sensor" (left sum) and "Utility Meter" sensor
